Updates to VeinholeMonsters, Tiberium and SWs + minor stuff
Phobos-developers/YRpp pull request #17
Opened 2023-09-18 12:40 UTC by ZivDero

2023-10-13 14:12 UTC, Starkku requested changes
One small thing that should be addressed but other than that looks good to me.

2023-10-13 14:12 UTC, Starkku commented on BuildingClass.h
> +
This is unnecessary addition. This function is a virtual function and is available in `TechnoClass` under name `GetPipFillLevel()` currently.

2023-10-13 15:14 UTC, ZivDero commented on BuildingClass.h
> +
Done.

2023-11-26 22:15 UTC, Metadorius commented
@Starkku have you compared the stuff with our IDB? as in do I need to do that in case you didn't?

2023-12-09 19:24 UTC, Metadorius reviewed
Commendable work 👍 
Left some stuff to discuss or for reference if needed but otherwise should be mergeable.

2023-12-09 19:24 UTC, Metadorius commented on HouseClass.h
> +	long double GetWeedStoragePercentage()
```suggestion
	double WeedFraction()
```
At least that's what it is in my copy of mappings, also not sure what's `long` for

2023-12-09 19:24 UTC, Metadorius commented on ParticleClass.h
>  	DWORD  unknown_C8;
![image](https://github.com/Phobos-developers/YRpp/assets/17500545/1dfa099c-a63e-4122-9263-5b3501422333)

2023-12-09 19:24 UTC, Metadorius commented on SmudgeTypeClass.h
> +	static void __fastcall LoadFromIniList(int idxTheatre)
called `Init` in my IDB

2023-12-09 19:24 UTC, Metadorius commented on VeinholeMonsterClass.h
> +	bool* CellIndexesWithVeins;
Seems to be used in multiple places in TibClass at least, see end of the class:

```cpp
struct __declspec(align(8)) TiberiumClass
{
  AbstractTypeClass at;
  int Type;
  int Spread;
  double SpreadPercentage;
  int Growth;
  double GrowthPercentage;
  int Value;
  int Power;
  int Color;
  TypeList Debris;
  int Image;
  int __NumFrames;
  int __NumImages;
  int int_field_EC;
  int SpreadCount;
  TiberiumClass_Data *SpreadHeaps;
  bool *SpreadState;
  TiberiumClass_CellData *SpreadCellData;
  TimerClass __SpreadTimer;
  int GrowthCount;
  TiberiumClass_Data *GrowthHeaps;
  bool *GrowthState;
  TiberiumClass_CellData *GrowthCellData;
  TimerClass __GrowthTimer;
};

struct TiberiumClass_Data
{
  int Size;
  int Capacity;
  TiberiumClass_CellData **Heap;
  int Ptr1;
  int Ptr2;
};

struct TiberiumClass_CellData
{
  CellStruct Cell;
  float Score;
};
```

2023-12-09 19:24 UTC, Metadorius commented on VeinholeMonsterClass.h
> -	static void __fastcall InitVeiGrowhData(bool bAllocate = true)
this is the vei

2023-12-09 19:24 UTC, Metadorius commented on VeinholeMonsterClass.h
> +	static void __fastcall DeleteVeinholeGrowthData()
called Spread, not Growth in mine

2023-12-09 19:24 UTC, Metadorius commented on VeinholeMonsterClass.h
> +	static void __fastcall LoadVeinholeArt(int idxTheatre)
called Init in mine

2023-12-09 19:24 UTC, Metadorius commented on VeinholeMonsterClass.h
> +	static void __cdecl UpdateAllVeinholes()
this is called `Remove_All_Veinhole_Monsters` in mine, possibly an error in IDB?

2023-12-09 19:26 UTC, Metadorius commented on TiberiumClass.h
>  	CDTimerClass Timer;
Wait didn't notice the duplication. Guess it will be good to generalize that in future.

2024-01-02 13:37 UTC, ZivDero commented on HouseClass.h
> +	long double GetWeedStoragePercentage()
Probably nothing.

2024-01-02 13:41 UTC, ZivDero commented on VeinholeMonsterClass.h
> +	static void __cdecl UpdateAllVeinholes()
Most likely an error in the IDB, yes.

2024-01-02 13:48 UTC, Metadorius approved these changes

2024-01-02 13:49 UTC, merged